version: '3.8'

services:
  avalanche:
    image: avalanchego-subnet-evm
    container_name: avalanchego
    restart: unless-stopped
    command:
      [
        "--config-file=/home/.avalanchego/configs/config.json",
        "--public-ip=<ENTER YOUR EXTERNAL IP>"
      ]
    volumes:
      - "${PWD}/avalanchego:/data/.avalanchego"
    ports:
      # Health and Monitoring TCP (Default: 9100)
      - "127.0.0.1:9100:9100"
      # Localhost-only binding for API access
      # HTTP API Json TCP (Default: 9650)
      - "127.0.0.1:9650:9650"
      # Consensus Server (Default: 9651)
      - "9651:9651/tcp"
      - "9651:9651/udp"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
